#define K2_DEBUG_WARN

#include "plat.h"
#include "utils.h"
#include "mmu.h"
#include "entry.h"

#ifdef PLAT_VIRT
#include "gic.h"
#endif

// must match entry.h 
const char *entry_error_messages[] = {
    [SYNC_INVALID_EL1t] "SYNC_INVALID_EL1t",
    [IRQ_INVALID_EL1t] "IRQ_INVALID_EL1t",		
    [FIQ_INVALID_EL1t] "FIQ_INVALID_EL1t",		
    [ERROR_INVALID_EL1t] "ERROR_INVALID_EL1t",		

    [SYNC_INVALID_EL1h] "SYNC_INVALID_EL1h",		
    [FIQ_INVALID_EL1h] "FIQ_INVALID_EL1h",		
    [ERROR_INVALID_EL1h] "ERROR_INVALID_EL1h",		

    [FIQ_INVALID_EL0_64] "FIQ_INVALID_EL0_64",		
    [ERROR_INVALID_EL0_64] "ERROR_INVALID_EL0_64",	

    [SYNC_INVALID_EL0_32] "SYNC_INVALID_EL0_32",		
    [IRQ_INVALID_EL0_32] "IRQ_INVALID_EL0_32",		
    [FIQ_INVALID_EL0_32] "FIQ_INVALID_EL0_32",		
    [ERROR_INVALID_EL0_32] "ERROR_INVALID_EL0_32",

    [SYNC_ERROR]    "Unhandled EL0 sync exception",
    [SYSCALL_ERROR] "SYSCALL_ERROR",
    [DATA_ABORT_ERROR] "Unhandled EL0 data abort (after kernel's trying)"
};

// Enables Core 0 Timers interrupt control for the generic timer 
void enable_interrupt_controller(int coreid)
{
#if defined(PLAT_RPI3) || defined(PLAT_RPI3QEMU)
    // On RPi3, Arm Generic timer IRQs are wired to a per-core interrupt controller/register. 
    // For core 0, this is `TIMER_INT_CTRL_0` at 0x40000040; bit 1 is for physical timer at EL1 (CNTP). This register is documented 
    // in the [manual](https://www.raspberrypi.org/documentation/hardware/raspberrypi/bcm2836/QA7_rev3.4.pdf) of BCM2836 
    // (search for "Core timers interrupts"). Note the manual is NOT for the BCM2837 SoC used by Rpi3    
    put32va(TIMER_INT_CTRL_0 + 4*coreid, TIMER_INT_CTRL_0_VALUE);

    put32va(ENABLE_IRQS_1, 
                ENABLE_IRQS_1_USB |\
                ENABLE_IRQS_1_AUX | \
                ENABLE_IRQS_1_DMA(12) |\
                SYSTEM_TIMER_IRQ_1); 

#elif defined(PLAT_VIRT)
    arm_gic_dist_init(0 /* core */, VA_START + QEMU_GIC_DIST_BASE, 0 /*irq start*/);
    arm_gic_cpu_init(0 /* core*/, VA_START + QEMU_GIC_CPU_BASE);
    arm_gic_umask(0 /* core */, IRQ_ARM_GENERIC_TIMER);
    arm_gic_umask(0 /* core */, IRQ_UART_PL011);
    arm_gic_umask(0 /* core */, IRQ_VIRTIO0);

    // finding irq numbers, which I couldn't find figure out (qemu info qtree? trace events)?
    // for (int i=0; i<64; i++)
    //     arm_gic_umask(0, i);
    // gic_dump(); // debugging 
#else   
    #error "unimplemented"    
#endif
}

// called from hw irq handler (el1_irq, entry.S)
#if defined(PLAT_RPI3) || defined(PLAT_RPI3QEMU)

typedef void TInterruptHandler (void *pParam); 
TInterruptHandler *usb_irq = 0;         // to be filled by usb driver
void *usb_irq_param = 0; 

TInterruptHandler *vchiq_irq = 0;    // to be filled by sound driver
void *vchiq_irq_param = 0; 

TInterruptHandler *dma_irq = 0;    // to be filled by pwm sound driver
void *dma_irq_param = 0; 

// cf: Circle CMultiCoreSupport::LocalInterruptHandler
void handle_irq(void) {
    // Interrupt controller can help us with this job: it has `INT_SOURCE_0` 
    // register that holds interrupt status for interrupts `0 - 31`. 
    // Using this register we can check whether the current interrupt was 
    // generated by the timer or by some other device and call device specific 
    // interrupt handler
    // NB: Each Core has its own pending local interrupt register. 
    int coreid = cpuid();
    unsigned int irq = get32va(INT_SOURCE_0 + 4*coreid), irq0 = irq; 

    if (irq & GENERIC_TIMER_INTERRUPT) {
        handle_generic_timer_irq();
        irq &= (~GENERIC_TIMER_INTERRUPT);
    } 
    
    // TODO: refactor cf sound/sample/env.c _int_irq()
    if (irq & GPU_SIDE_INTERRUPT) {
        unsigned int p1 = get32va(IRQ_PENDING_1);
        if (p1 & IRQ_PENDING_1_AUX) {
            uartintr(); 
            p1 &= (~IRQ_PENDING_1_AUX); 
        }
        if (p1 & SYSTEM_TIMER_IRQ_1) {
            sys_timer_irq(); 
            p1 &= (~SYSTEM_TIMER_IRQ_1);
        }
        if (p1 & IRQ_PENDING_1_USB) {
            V("IRQ_PENDING_1_USB"); 
            BUG_ON(!usb_irq);   // usb irq fired. no usb isr though
            (*usb_irq)(usb_irq_param); 
            p1 &= (~IRQ_PENDING_1_USB); 
        }
        for (int i = 0; i <= 12; i++) { // check 13 dma channels
            if (p1 & IRQ_PENDING_1_DMA(i)) {
                V("IRQ_PENDING_1_DMA %d", i); 
                if (dma_irq)
                    dma_irq(dma_irq_param); 
                p1 &= (~IRQ_PENDING_1_DMA(i));
            }
        }
        if (p1) {
            W("unknown pending irq in IRQ_PENDING_1"); 
            goto unknown; 
        }
        // TODO: check IRQ_PENDING_2
        unsigned pend_base = get32va(IRQ_BASIC_PENDING); 
        if (pend_base & 0xff) { 
            if (__builtin_ctz(pend_base & 0xff) == 2) // bit2:doorbell0
                (*vchiq_irq)(vchiq_irq_param); 
        }
        irq &= (~GPU_SIDE_INTERRUPT);               
    } 

    if (!irq) 
        return;  // all irq bits cleared

unknown:
    E("Unknown pending irq: INT_SOURCE_0 %08x IRQ_BASIC_PENDING %08x " 
            "IRQ_PENDING_1 %08x IRQ_PENDING_2 %08x\r\n", 
        irq0, 
        get32va(IRQ_BASIC_PENDING), 
        get32va(IRQ_PENDING_1),
        get32va(IRQ_PENDING_2)
        );
    BUG(); 
}
#endif

#if defined(PLAT_VIRT)
void handle_irq(void) {
    uint64_t cpu = 0; 
    
    int irq = arm_gic_get_active_irq(cpu);
    arm_gic_ack(cpu, irq);

    switch (irq) {
        case (IRQ_ARM_GENERIC_TIMER):
            handle_generic_timer_irq();
            break;
        case IRQ_UART_PL011:
            uartintr();
            break; 
        case IRQ_VIRTIO0:
            virtio_disk_intr();
            break; 
        default:
            printf("Unknown irq: %d\r\n", irq);
    }
}
#endif


// esr: syndrome, elr: ~faulty pc, far: faulty access addr
void show_invalid_entry_message(int type, unsigned long esr, 
    unsigned long elr, unsigned long far)
{    
    E("%s, cpu%d, esr: 0x%016lx, elr: 0x%016lx, far: 0x%016lx",  
        entry_error_messages[type], cpuid(), esr, elr, far);
    E("online esr decoder: %s0x%016lx", "https://esr.arm64.dev/#", esr);
    // TODO: dump FAR
}
