#!/usr/bin/python3 

# modeled after xv6 usys.pl. to auto gen user syscall stubs

print("# generated by usys.py -- do not edit")  
print("#  ./usys.py  > user_sys.S ")

print('''.section ".text.user" ''')
print('''#include "syscall.h" ''')

def entry(name): 
    print('''
.globl call_sys_{0}
    call_sys_{0}:
    mov x8, #SYS_{0}
    svc #0
    ret          
          '''.format(name))
        
entry("fork")
entry("exit")
entry("wait")
entry("pipe") 
entry("read") 
entry("write") 
entry("close") 
entry("kill") 
entry("exec") 
entry("open") 
entry("mknod") 
entry("unlink") 
entry("fstat") 
entry("link") 
entry("mkdir") 
entry("chdir") 
entry("dup") 
entry("getpid") 
entry("sbrk") 
entry("sleep") 
entry("uptime") 
entry("lseek") 